---
# tasks file for webserver
- name: Allow http access in ufw
  community.general.ufw:
    rule: allow
    port: http
    state: enabled

- name: Allow https access in ufw
  community.general.ufw:
    rule: allow
    port: https
    state: enabled
