---
# tasks file for common

- name: Create group for non root user
  ansible.builtin.group:
    name: janek
    gid: 1000
    state: present

- name: Create non root user
  ansible.builtin.user:
    name: janek
    password: "*"
    uid: 1000
    home: "/home/janek"
    shell: /bin/bash
    group: janek
    groups: janek,sudo
    append: true

# User's password is disabled, so wouldn't be able to use sudo with a password
- name: Allow passwordless sudo for non root user
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "janek  ALL=(ALL) NOPASSWD: ALL"

- name: Add ssh key to authorized_keys
  ansible.posix.authorized_key:
    key: "{{ lookup('file', '~/.ssh/terraform.pub') }}"
    user: janek
    state: present

- name: Make sure ssh directory and its contents have proper permissions
  ansible.builtin.file:
    path: /home/janek/.ssh
    mode: "0700"
    owner: janek
    group: janek
    recurse: true

- name: Harden ssh configuration
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item.name }} "
    line: "{{ item.name }} {{ item.value }}"
  loop: "{{ common_ssh_conf_list }}"
  notify: Restart ssh

- name: Install packages
  ansible.builtin.apt:
    name: "{{ common_package_list }}"
    state: present
    update_cache: true
    cache_valid_time: 120

- name: Allow ssh access in ufw
  community.general.ufw:
    rule: allow
    port: ssh
    state: enabled
