version: '3.8'

services:
  # Reverse Proxy
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${PERSISTENT_VOLUME_PATH}/nginx/:/etc/nginx/conf.d/"
      - "${PERSISTENT_VOLUME_PATH}/letsencrypt:/etc/letsencrypt"
    restart: unless-stopped
    networks:
      - webserver

  # Database
  db:
    image: mysql:8.2
    hostname: db
    volumes:
      - ${PERSISTENT_VOLUME_PATH}/mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - database

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    hostname: wordpress
    restart: unless-stopped
    volumes:
      - "${PERSISTENT_VOLUME_PATH}/wordpress:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - database
      - webserver

networks:
  webserver:
  database:
