---
- name: Configure a Wordpress web server
  hosts: webserver
  remote_user: "{{ login_user | default('janek') }}"
  become: true
  roles:
    - role: common
      common_user_name: janek
      common_user_group: janek
    - role: docker
    - role: webserver
      webserver_website_url: www.jzarzycki.com
      webserver_email: jzarzycki97@gmail.com
